# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Reward scoring function for the GSM-MC-Stage dataset (multiple choice).
"""
import re

# We enforce the model to output the choice letter after '####'
# e.g., '...is 42. #### C'
# The final answer must be a single uppercase letter A, B, C, or D.

def extract_choice(solution_str):
    """
    Extracts the final multiple-choice letter from the model's output.
    """
    # Regex to find '####' followed by optional spaces and then a single letter (A, B, C, or D)
    # The letter is captured in a group.
    # We clip the string to look near the end, where the final answer should be.
    _SOLUTION_CLIP_CHARS = 300
    if len(solution_str) > _SOLUTION_CLIP_CHARS:
        solution_str = solution_str[-_SOLUTION_CLIP_CHARS:]

    # Search for "#### " followed by an optional space, then a choice letter
    match = re.search(r"####\s*([A-D])", solution_str)

    if match:
        return match.group(1)
    else:
        # If the required format '#### X' is not found, return None
        return None


def compute_score(solution_str, ground_truth, method="strict", format_score=0.0, score=1.0):
    """The scoring function for GSM-MC-Stage.

    Args:
        solution_str: the solution text generated by the model
        ground_truth: the ground truth choice letter (e.g., 'A', 'B')
        method: unused, kept for API compatibility
        format_score: the score for correct formatting but incorrect answer
        score: the score for the correct answer
    """
    # 1. Extract the model's final answer (the choice letter)
    model_choice = extract_choice(solution_str=solution_str)

    if model_choice is None:
        # The model failed to follow the required format (#### A/B/C/D)
        return 0.0
    else:
        # 2. Compare the extracted choice with the ground truth
        if model_choice.strip() == ground_truth.strip():
            # Correct answer (and correct format due to extraction success)
            return score
        else:
            # Incorrect answer (but correct format since extraction succeeded)
            return format_score
